name: getui
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity: ^3.5.0
  flutter_getui:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
